<?php
/**
 * Mock product catalog.
 * Later, replace this array with a database query:
 *   $products = $pdo->query("SELECT * FROM products")->fetchAll();
 */

$products = [
    [
        'id'          => 1,
        'name'        => 'Wireless Headphones',
        'category'    => 'Electronics',
        'price'       => 89.99,
        'oldPrice'    => 129.99,
        'rating'      => 4.6,
        'image'       => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=70',
        'description' => 'Over-ear Bluetooth headphones with noise cancellation.',
        'inStock'     => true,
    ],
    [
        'id'          => 2,
        'name'        => 'Smart Watch Series 7',
        'category'    => 'Electronics',
        'price'       => 199.00,
        'oldPrice'    => 249.00,
        'rating'      => 4.8,
        'image'       => 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=70',
        'description' => 'Fitness tracking, heart-rate monitor, and 7-day battery.',
        'inStock'     => true,
    ],
    [
        'id'          => 3,
        'name'        => 'Leather Backpack',
        'category'    => 'Fashion',
        'price'       => 74.50,
        'oldPrice'    => null,
        'rating'      => 4.4,
        'image'       => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=70',
        'description' => 'Durable genuine-leather backpack with laptop sleeve.',
        'inStock'     => true,
    ],
    [
        'id'          => 4,
        'name'        => 'Running Sneakers',
        'category'    => 'Fashion',
        'price'       => 64.99,
        'oldPrice'    => 89.99,
        'rating'      => 4.5,
        'image'       => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=70',
        'description' => 'Lightweight running shoes with breathable mesh.',
        'inStock'     => true,
    ],
    [
        'id'          => 5,
        'name'        => 'Ceramic Coffee Mug Set',
        'category'    => 'Home',
        'price'       => 24.00,
        'oldPrice'    => null,
        'rating'      => 4.3,
        'image'       => 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=600&q=70',
        'description' => 'Set of 4 hand-glazed ceramic mugs, 350ml each.',
        'inStock'     => true,
    ],
    [
        'id'          => 6,
        'name'        => 'Minimal Desk Lamp',
        'category'    => 'Home',
        'price'       => 42.75,
        'oldPrice'    => 55.00,
        'rating'      => 4.7,
        'image'       => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=70',
        'description' => 'Adjustable LED desk lamp with warm & cool modes.',
        'inStock'     => true,
    ],
    [
        'id'          => 7,
        'name'        => 'Stainless Water Bottle',
        'category'    => 'Sports',
        'price'       => 19.99,
        'oldPrice'    => null,
        'rating'      => 4.2,
        'image'       => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=70',
        'description' => '500ml insulated bottle — keeps drinks cold 24h.',
        'inStock'     => true,
    ],
    [
        'id'          => 8,
        'name'        => 'Yoga Mat Pro',
        'category'    => 'Sports',
        'price'       => 34.99,
        'oldPrice'    => 44.99,
        'rating'      => 4.6,
        'image'       => 'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=600&q=70',
        'description' => 'Non-slip 6mm yoga mat with carrying strap.',
        'inStock'     => false,
    ],
    [
        'id'          => 9,
        'name'        => 'Bluetooth Speaker',
        'category'    => 'Electronics',
        'price'       => 59.00,
        'oldPrice'    => 79.00,
        'rating'      => 4.5,
        'image'       => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=70',
        'description' => 'Portable waterproof speaker with 12h playtime.',
        'inStock'     => true,
    ],
    [
        'id'          => 10,
        'name'        => 'Sunglasses Classic',
        'category'    => 'Fashion',
        'price'       => 29.99,
        'oldPrice'    => null,
        'rating'      => 4.1,
        'image'       => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=70',
        'description' => 'UV400 polarized sunglasses with hard case.',
        'inStock'     => true,
    ],
    [
        'id'          => 11,
        'name'        => 'Scented Candle Trio',
        'category'    => 'Home',
        'price'       => 27.50,
        'oldPrice'    => 35.00,
        'rating'      => 4.8,
        'image'       => 'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?auto=format&fit=crop&w=600&q=70',
        'description' => 'Soy-wax candles — lavender, vanilla, cedarwood.',
        'inStock'     => true,
    ],
    [
        'id'          => 12,
        'name'        => 'Football (Size 5)',
        'category'    => 'Sports',
        'price'       => 22.00,
        'oldPrice'    => null,
        'rating'      => 4.4,
        'image'       => 'https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&w=600&q=70',
        'description' => 'Match-grade football with reinforced stitching.',
        'inStock'     => true,
    ],
];